name: Testing the GitHub Pages publication

on:
  push

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:

    # Specify the Jekyll source location as a parameter
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.TOKEN }}
        jekyll_src: 'sample-site-b'
        gem_src: 'sample-site-b'
        target_branch: 'gh-pages'